using System.Reflection;

// Stockfish Visualizer Git@Sombody101

// Automatically generated by AssemblyInfo.tt on Saturday, September 09, 2023 01:52:52 AM

[assembly: AssemblyVersion("0.09.09.0152")]
[assembly: AssemblyFileVersion("0.09.09.0152")]
[assembly: AssemblyTitle("Stockfish Visualizer")]